### ISSUE TITLE
是否支持数据分片？

### ISSUE THREAD

**Issue by yangl** [nutzam/ssdb4j#1]
如题，commons-poll可以用2.2了

**Comment by bwzhang2011** [comment]
@wendal,  建议升级到commons pool2啊，或者起一个分支版本

**Comment by wendal** [comment]
@bwzhang2011 提交个pull req?

**Comment by bwzhang2011** [comment]
@wendal, 请查看 https://github.com/nutzam/ssdb4j/issues/20。
