### ISSUE TITLE
通过 ssdb4j 的 batch/exec 批量执行 1000 个 get() 获取已经存在的 1000 个键值对时，返回的结果不足

### ISSUE THREAD

**Issue by leonzhouwei** [nutzam/ssdb4j#17]
你好，我在试用 ssdb4j 的时候遇到这样一个问题，即通过 ssdb4j 的 batch/exec 批量执行 1000个 get() 获取事先准备的1000 个键值对时，每次都会出现返回结果不足 1000 的状况，而且在我这里是可以重现的。相关的测试用例代码和屏幕截图已经发到你的 gmail 邮箱，麻烦查收一下，谢谢。

**Comment by wendal** [comment]
76df65d48b92ffdbb2318e64408cd1e92532ae49
