### ISSUE TITLE
请教一个性能问题

### ISSUE THREAD

**Issue by furaul** [nutzam/ssdb4j#25]
最近刚接触ssdb，有一个问题求教。
使用ssdb4j作为java客户端，发现生产环境一次ttl（SSDB.ttl）的平均耗时在2ms左右，前后的代码中访问db的操作平均耗时只有0.8ms，db访问的是有索引的大表，这个数据是不是有问题？
或者是生产环境ssdb的服务端的配置导致的性能瓶颈？实际上ssdb的服务端压力并不大。

ps：生产环境机器的ping在0.13ms左右

**Comment by wendal** [comment]
上点代码看看?

**Comment by wendal** [comment]
是不是没用到连接池??

**Comment by wendal** [comment]
哦? 你封装流?

**Comment by furaul** [comment]
继承了SimpleClient，连接池配置就是上面的配置，然后直接调用SSDB.ttl()，实现就是SSDBClient.ttl(),单次调用耗时2ms。
只贴了相关的代码，其他代码没有贴上来。

**Comment by wendal** [comment]
```
poolConfig.testOnBorrow = true
```

网络稳定的话,这是多余的, 改成false

**Comment by wendal** [comment]
绝大多数情况下只会启用 testWhileIdle

**Comment by furaul** [comment]
已经修改，正在做测试。
还是问个问题，像我这样的生产配置，不等待连接资源，正产的单次访问耗时应该是多少？

**Comment by wendal** [comment]
测出来了吗?

**Comment by furaul** [comment]
优化效果是有的，但是单次调用耗时还是在1.5ms左右，同样代码中的oracle的操作耗时在1ms左右，感觉ssdb不应该比数据库慢啊。

**Comment by furaul** [comment]
我现在的耗时计算的平均值，我刚刚看了下我的统计数据，可能原因是极少部分耗时特别高，导致平均耗时较高，我先自己分析下。
感谢指导，感谢支持。
