### ISSUE TITLE
SSDB ssdb = SSDBs.pool("127.0.0.1", 8888, 2000); 创建一个,可以用多久?

### ISSUE THREAD

**Issue by w953999** [nutzam/ssdb4j#26]

**Comment by wendal** [comment]
一般都是放到静态属性了的啦, for ever咯

**Comment by w953999** [comment]
> 一般都是放到静态属性了的啦, for ever咯

明白了, 非常感谢 !!!!  感谢你的分享

**Comment by w953999** [comment]
请教一个问题, 本地开发是连接的服务器ip, 项目部署到ssdb所在服务器后, ip是服务器的外网ip地址, 这样去连接会影响性能吗, 是否需要判断后代码自适应的改为127.0.0.1

**Comment by wendal** [comment]
同一个机器的话, 没区别

**Comment by w953999** [comment]
> 同一个机器的话, 没区别

明白了, !!!
