### ISSUE TITLE
在使用springboot整合ssdb的时，注册配置文件bean后发现默认的maxTotal参数失效 导致ssdb链接数达到1000多

### ISSUE THREAD

**Issue by GrandioseCrazy** [nutzam/ssdb4j#27]
在使用springboot整合ssdb的时，注册配置文件bean后发现默认的maxTotal参数失效 导致ssdb链接数达到1000多，
配置的时候config是传的null，
`SSDBs.pool(host, port, timeout, null);` 在生产环境上跑起来后 ssdb链接数一度超过300 这一块是不是有小bug呀？

**Comment by wendal** [comment]
最新版？

**Comment by GrandioseCrazy** [comment]
您好，很高兴能够收到您的回复，我这边生产用的是10.0的这个版本，这边再本地调试发现要同时设置maxTotal和maxIdel后才能使得maxTotal生效，否则会超出大量链接！





------------------ 原始邮件 ------------------
发件人: "Wendal Chen"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 下午3:52
收件人: "nutzam/ssdb4j"<ssdb4j@noreply.github.com>;
抄送: "你是咔戈薇"<1400065562@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nutzam/ssdb4j] 在使用springboot整合ssdb的时，注册配置文件bean后发现默认的maxTotal参数失效 导致ssdb链接数达到1000多 (#27)




最新版？

**Comment by wendal** [comment]
最后一个参数传config对象就好了吧

**Comment by GrandioseCrazy** [comment]
我这边生产环境每秒并发500左右每秒，请问您这边建议maxTotal得设置是多少？万分感谢！

**Comment by GrandioseCrazy** [comment]
是的我这边传得config里把maxtotal设置后设置得是12 ， 发现连接数会超出

**Comment by wendal** [comment]
500吧...
